In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
# 1. Write a program to check whether an year entered by an user is leap year or not

# User enters the year
year = eval(input("Enter Year: "))

# Leap Year Check
if year % 4 == 0 and year % 100 != 0 or year %400==0:
    print(year, "is a Leap Year")
else:
    print(year, "is not a Leap Year")

Enter Year: 2012
2012 is a Leap Year


In [6]:
# 2. Take a string containing punctuation marks as an input from user and write a program to remove all the punctuation marks from a string

# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

#my_str = "Hello!!!, he said ---and went."

# To take input from the user
my_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

# give input value : "hello --my [best] friend

Enter a string: ----====CP
====CP


In [7]:
 # 3. Take two separate numbers as input from the user and Write a program to swap 2 numbers without using temporary variable
    
a = int(input(" enter the A number = "))
b = int(input(" enter the B number = "))
#temp = a 
#a = b 
#b = temp
a = a+b
b = a-b
a = a-b
print("after swappiing: ")
print("value of A : " ,a )
print("value of B : " ,b )

 enter the A number = 5
 enter the B number = 6
after swappiing: 
value of A :  6
value of B :  5


In [8]:
# 4. Write a program to print product of following variables
# we to use nested for loop which means for loop inside the for loop
integer = 10
string = "15"
product = integer*int(string)
product

150

In [13]:
# 5. Write a program to print following pattern

n = eval(input("Enter the number of rows :"))
k = ord("a")

for i in range(n):
    for j in range(i+1):
        print(chr(k), end = " ")
        k=k+1
    print()

Enter the number of rows :7
a 
b c 
d e f 
g h i j 
k l m n o 
p q r s t u 
v w x y z { | 


In [16]:
# 6. Write a program to print tables from 2 to n, where n is provided by user
a = 2
n = int(input(" enter the value of n :"))

for i in range(a,n+1):
    print(a,"*",n,"=",n*i)
    a+=1
    

# just enter the two tables multiplication tables will come 

 enter the value of n :6
2 * 6 = 12
3 * 6 = 18
4 * 6 = 24
5 * 6 = 30
6 * 6 = 36


In [37]:
#7.Write a program to read height (in centimeters) from user and then convert it to feet and inches:
cm=int(input("Enter the my height in centimeters:"))
inches=0.394*cm
feet=0.0328*cm
print("The length in inches",round(inches,2))
print("The length in feet",round(feet,2))

Enter the my height in centimeters:170
The length in inches 66.98
The length in feet 5.58


In [6]:
# 8. Write a program to print following pattern

n = int(input("enter the numbre of rows: "))
for i in range(n):
    for j in range(i):
        print ('* ', end="")
    print('')

for i in range(n,0,-1):
    for j in range(i):
        print('* ', end="")
    print('')

enter the numbre of rows: 5

* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [3]:
n=int(input('enter a number: '))
a=''
for i in range(n):
    print()
    a+='*'
    print(a,end='')
for i in range(n):
    print(a[0:-i])

enter a number: 5

*
**
***
****
*****
****
***
**
*


In [18]:
m=0
mr=eval(input('Enter a number: '))
for i in range(0,mr):
    m+=1
    for j in range(0,m):
        print('*',end=' ')
    print('\n')
    if m>(mr-1):
        for k in range(0,mr):
            m-=1
            for l in range(0,m):
                print('*',end=' ')
            print('\n')

Enter a number: 3
* 

* * 

* * * 

* * 

* 





In [121]:
# 9. Below list contains age and name of five students.
#Convert the list into a dictionary such that the name is taken as key and
# the age before their name is taken as thier respective value in the dictionary
#students = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton'] 
#Output: {'Jon':26, 'Roger':34, 'Jessica':13, 'Monica':24, 'Ashton':65}
    
def Convert(student):
    res_dct = {student[i + 1] :student[i] for i in range(0, len(student), 2)}
    return res_dct    

student = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton']
print(Convert(student))

{'Jon': 26, 'Roger': 34, 'Jessica': 13, 'Monica': 24, 'Ashton': 65}


In [22]:
#10. Write a program to check whether two strings, taken from user, are anagram or not
# IF SORT THE STRING ARE EQUAL THAT IS ANAGRAM # (DAD , ADD),(EARTH,HEART)
# SORT AND COMPARE
str1 = input("string 1 : ")
str2 = input("string 2 : ")
sorted_str1 = sorted(str1)
sorted_str2 = sorted(str2)

if sorted_str1 == sorted_str2:
    print("given string are Anagram")
else:
    print("given string are not anagram")


string 1 : dad
string 2 : bad
given string are not anagram


In [35]:
# 11. Write a program that sorts all the elements of the list according to the first letter,
#irrespective of their cases (uppercase or lowercase).
#Note: Do not use any inbuilt sorting function
num = int(input("how many numbers you want to enter ?"))
list1 = [int(input("enter the number :")) for x in range(num)]

print("unsorted_list : ", list1)

for i in range(len(list1)-1):
    m_ind = i
    for j in range(i+1,len(list1)):
        if  list1[j] < list1[m_ind]:
            m_ind = j
    if list1[i] != list1[m_ind]:
        list1[i],list1[m_ind] = list1[m_ind],list1[i]
print(list1)

how many numbers you want to enter ?6
enter the number :5
enter the number :26
enter the number :24
enter the number :15
enter the number :81
enter the number :5
unsorted_list :  [5, 26, 24, 15, 81, 5]
[5, 5, 15, 24, 26, 81]


In [45]:
# 12. Write a program that prints a list of sour fruits from the below tuple:
# fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','soUr'), ('Kiwi','Sour'), ('Apples','sweet'), ('Orange','sour'), ('Blueberries','sweet'), ('Limes','Sour') )
# Output: Sour Fruits: ['Lemon', 'Grapes', 'Kiwi', 'Orange', 'Limes']



fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','soUr'), 
          ('Kiwi','Sour'), ('Apples','sweet'), ('Orange','sour'), ('Blueberries','sweet'), ('Limes','Sour') )
li=[]
for i in fruits:
    if i[1].lower() == 'sour':
        li.append(i[0])
print("Sour fruits : ",li)

Sour fruits :  ['Lemon', 'Grapes', 'Kiwi', 'Orange', 'Limes']


In [2]:
# 13. 13. Given below are the list of positive and negative words. Also a list of tweets is provided.
#Separate out the positive and negative comments

positive = ['good','awesome', 'best', 'nice']

negative = ['worst','awful', 'bad']

tweets = ['This government policies are good', 'bad implementation', 
          'The way he played showed that he is one of the best players in the world', 
          'Her acting in the play was awesome', 'The wine tastes awful', 'Its nice to hear this little kids laugh']

postive_comments=[]
negative_comments=[]
for sentence in tweets:
    for word in sentence.split(' '):
        if word in positive:
            postive_comments.append(sentence)
        elif word in negative:
            negative_comments.append(sentence)
print('positive tweets are',postive_comments)
print('\n')
print('negative tweets are',negative_comments)

positive tweets are ['This government policies are good', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'Its nice to hear this little kids laugh']


negative tweets are ['bad implementation', 'The wine tastes awful']


In [13]:
import numpy as np

In [20]:
# 14. 14. Write a program that performs multiplication of the following two matrix

X = [[1,2,3],
     [4 ,5,6],
     [7 ,8,9]]
Y = [[1,8,1],
     [3,7,3],
     [4,5,9]]
print("original matrix: ")
print(X)
print(Y)
result = np.dot(X,Y)
print("result of matrix multiplication: ")
print(result)


original matrix: 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 8, 1], [3, 7, 3], [4, 5, 9]]
result of matrix multiplication: 
[[ 19  37  34]
 [ 43  97  73]
 [ 67 157 112]]


In [29]:
# 15. Write a program to remove space from keys of the given dictionary
Employee = {'emp 01' : 'Raj', 'emp 02' : 'Sheela', 'emp 0 3 ': 'Joseph'};
Employee =  {x.replace(' ',''): v 
     for x, v in Employee.items()}
print("New_dictionary: ",Employee)


New_dictionary:  {'emp01': 'Raj', 'emp02': 'Sheela', 'emp03': 'Joseph'}


In [29]:
# 16. Write a program to display the subjects for which the scores are between 300 and 500 (inclusive) in the given dataframe


df1 = pd.DataFrame ({
    "Subjects": ["Maths","Physics","Chemistry","Biology","Geology"],
    "Score": [345,432,456,234,254] ,
})

print("old dataframe : ", df1)

#max_val = df1.max()
#min_val = df1.min()
#print(max_val)
#print(min_val)

df2 = df1[df1["Score"]>=300]
print()


 

old dataframe :      Subjects  Score
0      Maths    345
1    Physics    432
2  Chemistry    456
3    Biology    234
4    Geology    254



In [36]:
# 28. Compute total sales for each product and country

data = pd.read_csv("C:/Users/chandraprakash/Documents/Book1.csv")
print("My original data ", data)

data1 = pd.crosstab(data.Country,data.Product)
print("cross tab table : ",data1)
data2 = data.pivot_table(index="Country",columns="Product",margins=True)
print("output of the table: ",data2)

My original data    Product Country  Sales
0       A     USA  44000
1       J   Japan  43000
2       A  Europe  54000
3       L   Japan  95600
4       R  Europe  79000
5       A     USA  67000
6       R     USA  68000
7       J   Japan  38000
8       L     USA  59000
9       A  Europe  60000
cross tab table :  Product  A  J  L  R
Country            
Europe   2  0  0  1
Japan    0  2  1  0
USA      2  0  1  1
output of the table:             Sales                                         
Product        A        J        L        R           All
Country                                                  
Europe   57000.0      NaN      NaN  79000.0  64333.333333
Japan        NaN  40500.0  95600.0      NaN  58866.666667
USA      55500.0      NaN  59000.0  68000.0  59500.000000
All      56250.0  40500.0  77300.0  73500.0  60760.000000


In [37]:
# 29. Get the descriptive statistics of the sales for each Country

data = pd.read_csv("C:/Users/chandraprakash/Documents/Book1.csv")
print("My original data ", data)

# descritive analytics count()sum()mean()median()mode()std()min()max()abs()prod()cumsum()cumprod()





My original data    Product Country  Sales
0       A     USA  44000
1       J   Japan  43000
2       A  Europe  54000
3       L   Japan  95600
4       R  Europe  79000
5       A     USA  67000
6       R     USA  68000
7       J   Japan  38000
8       L     USA  59000
9       A  Europe  60000


In [18]:
# 30. Reverse each of the rows of the 2D array

num_array = np.arange(20).reshape(4,5)

print("normal array : ", num_array)

res = [sorted(sub, reverse = True) for sub in num_array]

print("reversed arrayy:", res)

normal array :  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
reversed arrayy: [[4, 3, 2, 1, 0], [9, 8, 7, 6, 5], [14, 13, 12, 11, 10], [19, 18, 17, 16, 15]]
