#    <img src='image2.jpg'></img>


<html>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
<font color='FF3407' size='16'><i class="fa fa-bar-chart" style="font-size:48px;"></i>&nbsp;
&nbsp;
<b>Data Analytics</b></font></html>

# <font color='#ff9900' size="50">NUMERICAL PYTHON PRESENTED BY</font>
<br>
<br>


### <font color='manaco'>1) BABU<font color ='blue' size='5'>&#127891;</font></font>

# <u><font color='996600'>NUMPY FUNCTIONS AND METHODS</font></u>

##  <u><font color='996600'>NUMPY METHODS()</font></u>

## <font color='red'>1) SQUEEZE()</font> 

# <html><font size='6' color='red'>&#9829;</font></html> <font face='Courier'> Selects subset of single dimensional entries in shape of &nbsp;&nbsp;array</font>
# <html><font size='6' color='red'>&#9829;</font></html> <font face='Courier'> Reduce the dimensions of Array</font>

In [1]:
import numpy as np

In [2]:
input_array = np.array([[[[[[(1, 2, 3), (4, 5, 6)]]]]]])

In [3]:
input_array

array([[[[[[[1, 2, 3],
            [4, 5, 6]]]]]]])

In [4]:
input_array.shape

(1, 1, 1, 1, 1, 2, 3)

In [5]:
output_array = np.squeeze(input_array)

In [6]:
output_array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
output_array.shape

(2, 3)

### <u><font color='#b3003b'> [SLICING  IN DIMENSIONAL ARRAY]</font></u>

In [131]:
output_array[1][2]

6

In [143]:
input_array[0][0][0][0][0][1][1]

5

##  <font color='red'>2) SWAPAXES()</font> 
# <html><font size='6' color='red'>&#9829;</font></html> <font face='Courier'>Changes the row and column Axes of Array.</font>

In [10]:
x = np.array([[1,2,3]]) 
x

array([[1, 2, 3]])

In [11]:
rowaxes = np.swapaxes(x,1,1)
rowaxes

array([[1, 2, 3]])

In [149]:
 colaxes=np.swapaxes(x,0,1)
colaxes

array([[1],
       [2],
       [3]])

### <u><font color='#b3003b'> [SLICING  IN DIMENSIONAL ARRAY]</font></u>

In [13]:
colaxes[0][0]

1

In [14]:
colaxes[2][0]

3

##  <font color='red'>3) SETFIELD() <font color='green'>and</font> GETFIELD()</font> 

# <html><font size='6' color='red'>&#9829;</font></html> <font face='Courier'>Put a value into a specified place in a field defined by a &nbsp;&nbsp;&nbsp;data-type.</font>
# <html><font size='6' color='red'>&#9829;</font></html><font face='Courier' size='5' color='black'> Returns a field of the given array as a certain type.A field is a &nbsp;&nbsp;view of the array data with a given data-type.</font>

In [19]:
x1=np.eye(7)

In [20]:
x1

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### <u><font color='#b3003b'> [SLICING  IN DIMENSIONAL ARRAY]</font></u>

In [21]:
x1[4,4:5]

array([1.])

In [22]:
x1.setfield(7, np.int32)
np.trace(x1)

7.0000000000000115

In [23]:
x1.getfield(np.int32)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

##  <font color='red'>4) TRACE() <font color='green'>and</font> DUMPS()</font> 

In [18]:
x1= np.eye(6)

In [19]:
x1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
x2=x1.setfield(6,np.int64)
x2=x1.getfield(np.int64)
x2

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]], dtype=int64)

### <font color='e68319'>[i] trace()</font>

# <html><font size='6' color='red'>&#9829;</font></html> <font face='Courier'>Trace is used for sum of diagonal elements</font>

In [23]:
np.trace(x1)

1.8e-322

In [21]:
np.trace(x2)

36

### <font color='e68319'>[ii] dumps()</font>

 # <html><font size='6' color='red'>&#9829;</font></html> <font face='Courier'>dumps is used to convert array into unicode string </font>

In [1]:
import numpy as np
z1= np.array([[2,5,7],[3,8,4],[4,9,1]])

In [2]:
z1

array([[2, 5, 7],
       [3, 8, 4],
       [4, 9, 1]])

In [4]:
a =np.ndarray.dumps(z1)
a

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x03K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X$\x00\x00\x00\x02\x00\x00\x00\x05\x00\x00\x00\x07\x00\x00\x00\x03\x00\x00\x00\x08\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\t\x00\x00\x00\x01\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

##  <font color='red'>5) FLIP() <font color='green'>and</font> FILL()</font> 

### <font color='e68319'>[i] flip()</font>

#  <html><font size='6' color='red'>&#9829;</font></html> <font face='Courier'>Filp will change the dimensions of the matrix </font>

In [28]:
z= np.array([[2,5,7],[3,8,4]])

In [29]:
z

array([[2, 5, 7],
       [3, 8, 4]])

In [121]:
np.flip(z)

array([[4, 8, 3],
       [7, 5, 2]])

In [154]:
np.flip(z,axis=0)

array([[3, 8, 4],
       [2, 5, 7]])

In [153]:
np.flip(z,axis=1)

array([[7, 5, 2],
       [4, 8, 3]])

### <font color='e68319'>[i] fill()</font>

In [117]:
zr=np.array([[[1,2,3,6],[4,6,8,3],[1,6,7,1],[2,9,3,4],[6,9,2,5]]])

In [118]:
zr

array([[[1, 2, 3, 6],
        [4, 6, 8, 3],
        [1, 6, 7, 1],
        [2, 9, 3, 4],
        [6, 9, 2, 5]]])

In [119]:
zr.fill(0)

In [120]:
zr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

###  <font color='red'>6) FLATTEN()</font>

In [4]:
a = np.array([[1,2,4], [7,8,9],[10,11,12]])
a

array([[ 1,  2,  4],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
a.flatten()

array([ 1,  2,  4,  7,  8,  9, 10, 11, 12])

In [5]:
x = np.array([[1,2,3],[4,5,6]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
y=x

In [8]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
y[1][1] = 0

array([[1, 2, 3],
       [4, 0, 6]])

In [9]:
z = np.copy(x)

In [10]:
z[1][1] = 1
z

array([[1, 2, 3],
       [4, 1, 6]])

###  <font color='red'>7) CLIP()</font>

# <html><font size='6' color='red'>&#9829;</font></html> <font face='Courier'>Clip function is used to clip  the values in array </font>

In [40]:
clip_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 

In [41]:
clip_array

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [174]:
out_array = np.clip(clip_array, a_min =4,a_max = 9) 

In [175]:
out_array

array([4, 4, 4, 4, 5, 6, 7, 8, 9, 9])


## <u><font color='996600'>NUMPY FUNCTIONS()</font></u>

### <font color='red'>1) SPLIT()</font>

# <html><font size='6' color='red'>&#9733;</font></html> <font face='Courier'> Split function used to split the strings based on the - &nbsp;&nbsp;input</font>

In [227]:
input_str_arr = np.array(['Today', 'we-have', 'a-p-r-esentation','in-our','class'])

In [228]:
print(input_str_arr)

['Today' 'we-have' 'a-p-r-esentation' 'in-our' 'class']


In [231]:
output_str_arr = np.char.split(input_str_arr, sep = '-')

In [232]:
print(output_str_arr)

[list(['Today']) list(['we', 'have']) list(['a', 'p', 'r', 'esentation'])
 list(['in', 'our']) list(['class'])]


### <font color='red'>2) LESS()</font>

# <html><font size='6' color='red'>&#9733;</font></html> <font face='Courier'> Less function used to compare the strings based on the given &nbsp;&nbsp;input</font>

In [237]:
array1=np.array(['HELO','Guys','Welcome','TO','PRESENTATION'])

In [244]:
array2=np.array(['helo','guys','WELCOME','TO','pRESENTATION'])

In [245]:
output_array =np.char.less(array1, array2) 

In [246]:
output_array

array([ True,  True, False, False,  True])

### <font color='red'>3) RFIND()</font>

# <html><font size='6' color='red'>&#9733;</font></html> <font face='Courier'> RFind function used to find the highest index locations &nbsp;&nbsp;based on the given input</font>

In [52]:
find_array = np.array(['aAaAaA', 'aA', 'abBABba'])

In [53]:
find_array

array(['aAaAaA', 'aA', 'abBABba'], dtype='<U7')

In [54]:
array_output =np.char.rfind(find_array, sub ='a')

In [55]:
array_output

array([4, 0, 6])

In [56]:
find_array1 = np.array(['CcCcC', 'CC'])

In [57]:
array_output1 =np.char.rfind(find_array1, sub ='c')

In [58]:
array_output1

array([ 3, -1])

### <font color='red'>4) ZFILL()</font>

# <html><font size='6' color='red'>&#9733;</font></html> <font face='Courier'> ZFill function used to fill zeros after word placed in &nbsp;&nbsp;within given width</font> 

In [252]:
input_zfill = np.array(['always', 'be', 'happy']) 

In [253]:
input_zfill

array(['always', 'be', 'happy'], dtype='<U6')

In [255]:
width = 8

In [256]:
output_zfill = np.char.zfill(input_zfill, width) 

In [257]:
output_zfill

array(['00always', '000000be', '000happy'], dtype='<U8')

### <font color='red'>5) IS_ALPHA()</font>

# <html><font size='6' color='red'>&#9733;</font></html> <font face='Courier'> Is_Alpha function used to find complete string without &nbsp;&nbsp;&nbsp;having any symbols or numericals</font> 

In [64]:
alpha_input = np.array(['python', '1pyspark', 'f or', 'k eras', 'wow'] )

In [65]:
alpha_input

array(['python', '1pyspark', 'f or', 'k eras', 'wow'], dtype='<U8')

In [66]:
alpha_output = np.char.isalpha(alpha_input)

In [67]:
alpha_output

array([ True, False, False, False,  True])

### <font color='red'>6) SWAPCASE()</font>

# <html><font size='6' color='red'>&#9733;</font></html> <font face='Courier'> SwapCase is used to swap its case</font>  

In [68]:
swap_input = np.array(['Life', 'Is', 'Very','sHORT']) 

In [69]:
swap_input

array(['Life', 'Is', 'Very', 'sHORT'], dtype='<U5')

In [70]:
swap_output =np.char.swapcase(swap_input) 

In [71]:
swap_output

array(['lIFE', 'iS', 'vERY', 'Short'], dtype='<U5')

### <font color='red'>7) FLAGS</font>

# <html><font size='6' color='red'>&#9733;</font></html> <font face='Courier'> Array flags provide information about how the memory allocation &nbsp;&nbsp;&nbsp;used for the array is to be interpreted. </font>
# <html><font size='6' color='red'>&#9733;</font></html> <font face='Courier'>There are 7 Boolean flags in use, only four of &nbsp;&nbsp;&nbsp;which can be changed by the user: WRITEBACKIFCOPY, UPDATEIFCOPY, &nbsp;&nbsp;&nbsp;WRITEABLE, and ALIGNED</font>

In [84]:
Flag_array = np.array([[[1, 2, 3], [4, 5, 6]]])

In [85]:
Flag_array

array([[[1, 2, 3],
        [4, 5, 6]]])

In [86]:
Flag_array.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

### <font color='red'>7) SET FLAGS</font>

In [2]:
Flag_array1 = np.array([[[1, 2, 3], [4, 5, 6]]])

In [3]:
Flag_array1

array([[[1, 2, 3],
        [4, 5, 6]]])

In [4]:
 Flag_array1.setflags( write=0,align=0,)

In [5]:
Flag_array1.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : False
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

#        <img src='thank.jpg' width='9997'></img>

# ARRAY ATTRIBUTES AND METHODS

In [6]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

# RESHAPE

In [7]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# MAX, MIN, ARGMAX, ARGMIN

In [8]:
ranarr.max()

40

In [9]:
ranarr.argmax()# displays the position of the max value

9

In [10]:
ranarr.min()

7

In [11]:
ranarr.argmin()

3

In [12]:
# creating a sample array 
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])