In [1]:
import numpy as np

In [9]:
arr = np.array([[1]])
arr

array([[1]])

In [10]:
arr.shape

(1, 1)

In [13]:
arr1 = np.array([[1,2,3],[2,3,4]])
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [14]:
arr1.shape

(2, 3)

In [15]:
arr1.T.shape

(3, 2)

In [18]:
arr1[:1,:1]

array([[1]])

In [20]:
arr1[-1][-1]

4

In [21]:
arr1[-1][-1].ndim

0

In [27]:
dt = np.dtype('i1')
dt

dtype('int8')

In [31]:
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])

In [32]:
a = np.array([('vijay',33,100),('chandra',23,100)],dtype = student)

In [33]:
a['age']

array([33, 23], dtype=int8)

In [34]:
a['marks']

array([100., 100.], dtype=float32)

In [36]:
a.ndim

1

In [37]:
a.item

<function ndarray.item>

In [39]:
import numpy as np
a =  np.arange(2, 11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [40]:
a.itemsize #memory 4 bit size.

4

In [43]:
x = np.empty([3,3], dtype = int)

In [44]:
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
x = np.zeros([5,5] , dtype=float)
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
x = np.zeros([5,5] , dtype=str)
x

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [47]:
x = np.zeros([5,5] , dtype=int)
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [48]:
x = np.ones([5,5], dtype = int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
y = np.ones([5,5], dtype = int)
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
x + y

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [53]:
x - y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [55]:
a = [1,2,3,4,5,6]
b = [2,3,4,5,6,7]
a+b

[1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7]

In [56]:
list(np.asarray(a)+np.asarray(b)) # adding two elements using the code

[3, 5, 7, 9, 11, 13]

In [58]:
#slicing
g = np.array([[1,4,6,6,5],[1,3,5,7,9],[2,4,6,8,10],[1,5,4,8,6],[1,5,6,9,7]])
g

array([[ 1,  4,  6,  6,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 1,  5,  4,  8,  6],
       [ 1,  5,  6,  9,  7]])

In [62]:
print(g[2:,4 :])

[[10]
 [ 6]
 [ 7]]


In [63]:
g[slice(1,4,2)]

array([[1, 3, 5, 7, 9],
       [1, 5, 4, 8, 6]])

In [66]:
g[slice(1,4,)]

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 1,  5,  4,  8,  6]])

In [67]:
tab = np.array([[100,12,11],[12,120,16],[23,12,135]])
tab

array([[100,  12,  11],
       [ 12, 120,  16],
       [ 23,  12, 135]])

In [68]:
tab[0][0]+tab[1][1]+tab[2][2]

355

In [73]:
tab[0][0]+tab[1][1]+tab[2][2]/s

220.30612244897958

In [69]:
s = 0
for i in tab:
    for j in i:
        s+=j
s

441

In [74]:
tab.diagonal().sum()/tab.sum()

0.8049886621315193

In [75]:
tab

array([[100,  12,  11],
       [ 12, 120,  16],
       [ 23,  12, 135]])

In [82]:
max_value = np.max(tab[0])

max_value

100

In [84]:
np.amax(tab)

135

In [85]:
np.amax(tab, axis=0)

array([100, 120, 135])

In [86]:
for i in range(3):
    for j in range(3):
        if tab[i][j]==max(tab[i]):
            print(i)

0
1
2


In [92]:
pos = []
for i in tab:
    max_num = max(i)
    pos.append(list(i).index(max_num))
pos

[0, 1, 2]

In [ ]:
a.dot(b)# matrics multiplication